### PR TITLE
[fix] adds back support for falsy front matter values e.g. eof_last

### PR DESCRIPTION
**Pull request by chrishale**
In reference to #146 and #165

### CODE REVIEW

**Comment by jondot** [comment]
Thanks!

**Comment by chrishale** [comment]
Don't think this made it into the 5.0.2 release. I didn't do a dist build in my commit, I only changed the src file. Sorry for the confusion!

**Comment by jondot** [comment]
got catch. should be fixed now (build is in progress)

**Comment by chrishale** [comment]
Fantastic, thanks!

**Pull request merged**
