### PR TITLE
Add change case helpers (#63)

### PR DESCRIPTION
**Pull request by lamartire**
Hello @jondot!
Like I said in #63 – it's my vision of really useful helpers for text case transforming.
Hope you like it ✨

### CODE REVIEW

**Comment by lamartire** [comment]
I also fixed jest builds in app veyor and if you will accept `changeCase` helpers, I will update some docs with that feature and some template moments.

**Comment by lamartire** [comment]
Awww, [all tests passed](https://ci.appveyor.com/project/jondot/hygen/builds/20598255/job/mqtw0hqco64w93w5#L271), but jest dropped with code 1. I think it is not problem of code 😄

**Comment by jondot** [comment]
I love it!
Thanks!

**Comment by lamartire** [comment]
🎉

**Pull request merged**
