### PR TITLE
pass commandline args to prompt

### PR DESCRIPTION
**Pull request by bobbor**
this introduces the possibility to return a function from prompt.
that function would be passed in the arguments

### CODE REVIEW

**Comment by jondot** [comment]
AWESOME! I totally didn't see that coming :)
Is there a chance you can add a couple tests for your added functionality?

**Comment by jondot** [comment]
@bobbor ping :) just LMK if you can add tests. if not it's completely fine, I'll do my best to add those tests to your code.

**Comment by tobmaster** [comment]
Hehe I wanted that too. 
Only that I was thinking about doing it slightly different and expose the args to the prompt.js file. 
That way I could also use the arguments to do some conditional questioning depending on the presence of a value.
But it would require to load the prompt via a constructor/factory method instead of just require.
For example
```
const prompt = require(promptfile).getPrompt(args)
```

Another way could be by using an argument provider that you could require in the prompt.js file. 

What you people think about those ideas?

**Comment by jondot** [comment]
@tobmaster good news! it looks like with yesterday's support for recursive prompts, we can combine your solution with the PR here. I'll take a stab at it

**Comment by jondot** [comment]
@tobmaster done. you can read about recursive prompts here: www.hygen.io/generators#advanced-prompts

@bobbor please take note that in order to support both use cases I resolved the conflict  in a way that might break existing interfaces you might have.
Specifically there's a `prompt` function in `prompt.js` that's exported and it gets two fields in one object:

so from 

```
prompt(args)
```

it becomes

```
prompt({ inquirer, args })
```

**Comment by tobmaster** [comment]
Just to show you what i did before. My hack to achive it was as follows in prompt.js:
```
const argv = require('yargs-parser')(process.argv);
module.exports = [
  {
    type: 'input',
    name: 'service',
    message: "Mind gimme a service name?",
    when: !argv.service
},...];
```

**Comment by tobmaster** [comment]
Ah nice :) Thx

**Comment by jondot** [comment]
I'll add the tests now + docs. Have some time to kill on the train

**Comment by bobbor** [comment]
was about to pick it up after dinner, but alright... 👍

**Comment by jondot** [comment]
Merged!
Folks: notice I've summed up all changes, of both ideas in the docs, with a little bit of rewording to even take out another long-standing idea in a separate issue (reshaping arguments for all templates in one place)
http://www.hygen.io/generators#advanced-params (may take a while until docs are rebuilt and pushed)

**Comment by jondot** [comment]
I'll give everything a bit of time to build and then cut a new version that you can start playing with this

**Comment by jondot** [comment]
@bobbor @tobmaster hey guys, I'm working on a new section for the landing page, something along the lines of "Friends of Hygen", where I'll put logos and links of companies that use Hygen (free).
Would any of you want to take part? if so, ping me at dotan@paracode.com 😎

**Pull request merged**
